// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audiobuffer_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_audiobuffer_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_audiobuffer_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_audiobuffer_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_audiobuffer_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_audiobuffer_5fservice_2eproto;
namespace lemonade {
class AudoBufferClientRequest;
struct AudoBufferClientRequestDefaultTypeInternal;
extern AudoBufferClientRequestDefaultTypeInternal _AudoBufferClientRequest_default_instance_;
}  // namespace lemonade
PROTOBUF_NAMESPACE_OPEN
template<> ::lemonade::AudoBufferClientRequest* Arena::CreateMaybeMessage<::lemonade::AudoBufferClientRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lemonade {

// ===================================================================

class AudoBufferClientRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lemonade.AudoBufferClientRequest) */ {
 public:
  inline AudoBufferClientRequest() : AudoBufferClientRequest(nullptr) {}
  ~AudoBufferClientRequest() override;
  explicit PROTOBUF_CONSTEXPR AudoBufferClientRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AudoBufferClientRequest(const AudoBufferClientRequest& from);
  AudoBufferClientRequest(AudoBufferClientRequest&& from) noexcept
    : AudoBufferClientRequest() {
    *this = ::std::move(from);
  }

  inline AudoBufferClientRequest& operator=(const AudoBufferClientRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudoBufferClientRequest& operator=(AudoBufferClientRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudoBufferClientRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudoBufferClientRequest* internal_default_instance() {
    return reinterpret_cast<const AudoBufferClientRequest*>(
               &_AudoBufferClientRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AudoBufferClientRequest& a, AudoBufferClientRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AudoBufferClientRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudoBufferClientRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudoBufferClientRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AudoBufferClientRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AudoBufferClientRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AudoBufferClientRequest& from) {
    AudoBufferClientRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudoBufferClientRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lemonade.AudoBufferClientRequest";
  }
  protected:
  explicit AudoBufferClientRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLengthFieldNumber = 1,
    kDatabufferFieldNumber = 2,
  };
  // required int32 length = 1;
  bool has_length() const;
  private:
  bool _internal_has_length() const;
  public:
  void clear_length();
  int32_t length() const;
  void set_length(int32_t value);
  private:
  int32_t _internal_length() const;
  void _internal_set_length(int32_t value);
  public:

  // optional int32 databuffer = 2;
  bool has_databuffer() const;
  private:
  bool _internal_has_databuffer() const;
  public:
  void clear_databuffer();
  int32_t databuffer() const;
  void set_databuffer(int32_t value);
  private:
  int32_t _internal_databuffer() const;
  void _internal_set_databuffer(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:lemonade.AudoBufferClientRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int32_t length_;
    int32_t databuffer_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_audiobuffer_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AudoBufferClientRequest

// required int32 length = 1;
inline bool AudoBufferClientRequest::_internal_has_length() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AudoBufferClientRequest::has_length() const {
  return _internal_has_length();
}
inline void AudoBufferClientRequest::clear_length() {
  _impl_.length_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t AudoBufferClientRequest::_internal_length() const {
  return _impl_.length_;
}
inline int32_t AudoBufferClientRequest::length() const {
  // @@protoc_insertion_point(field_get:lemonade.AudoBufferClientRequest.length)
  return _internal_length();
}
inline void AudoBufferClientRequest::_internal_set_length(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.length_ = value;
}
inline void AudoBufferClientRequest::set_length(int32_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:lemonade.AudoBufferClientRequest.length)
}

// optional int32 databuffer = 2;
inline bool AudoBufferClientRequest::_internal_has_databuffer() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AudoBufferClientRequest::has_databuffer() const {
  return _internal_has_databuffer();
}
inline void AudoBufferClientRequest::clear_databuffer() {
  _impl_.databuffer_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t AudoBufferClientRequest::_internal_databuffer() const {
  return _impl_.databuffer_;
}
inline int32_t AudoBufferClientRequest::databuffer() const {
  // @@protoc_insertion_point(field_get:lemonade.AudoBufferClientRequest.databuffer)
  return _internal_databuffer();
}
inline void AudoBufferClientRequest::_internal_set_databuffer(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.databuffer_ = value;
}
inline void AudoBufferClientRequest::set_databuffer(int32_t value) {
  _internal_set_databuffer(value);
  // @@protoc_insertion_point(field_set:lemonade.AudoBufferClientRequest.databuffer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace lemonade

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_audiobuffer_5fservice_2eproto
